using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventHub.Infrastructure.Migrations
{
    /// <summary>
    /// Adds the AIConversations/AIMessages tables backing the new AI Planner
    /// feature (AIPlannerController, AIConversation/AIMessage entities).
    ///
    /// PRE-PUSH REVIEW NOTE: this file was hand-written (not generated by
    /// `dotnet ef migrations add`) because no .NET SDK was available to run
    /// the EF CLI in the environment that reviewed this change. It mirrors
    /// the column types / key / FK conventions used by the comparable
    /// tables in 20260805171711_InitialCreate.cs (SoftDeletableEntity ->
    /// Events/WorkPosts pattern for AIConversation, Cascade FK-only pattern
    /// for AIMessage) as closely as possible. It intentionally has NO
    /// accompanying .Designer.cs and ApplicationDbContextModelSnapshot.cs
    /// was NOT updated — hand-writing those (a full model snapshot, not
    /// just a diff) is too error-prone without the tooling to verify it.
    ///
    /// Before relying on this: run `dotnet ef migrations add AddAIPlanner`
    /// on a machine with the .NET SDK — if the model already matches this
    /// migration, EF will report "no changes"; if anything here is off, it
    /// will generate a small corrective migration on top. Either way, that
    /// command is also what regenerates a correct Designer.cs/snapshot.
    /// </summary>
    // Normally this attribute lives on the auto-generated .Designer.cs
    // partial class alongside a full BuildTargetModel() snapshot — placed
    // directly here instead since that file isn't included (see the class
    // doc comment above). This is enough for EF to discover, order, and
    // apply the migration via `dotnet ef database update`; it's the
    // snapshot-diffing used by `migrations add` for the *next* migration
    // that needs the real tooling to regenerate correctly.
    [Migration("20260807000000_AddAIPlannerTables")]
    public partial class AddAIPlannerTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AIConversations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EventId = table.Column<int>(type: "int", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false, defaultValue: "New Conversation"),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedBy = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AIConversations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AIConversations_Events_EventId",
                        column: x => x.EventId,
                        principalTable: "Events",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AIMessages",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AIConversationId = table.Column<int>(type: "int", nullable: false),
                    Sender = table.Column<int>(type: "int", nullable: false),
                    Content = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AIMessages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AIMessages_AIConversations_AIConversationId",
                        column: x => x.AIConversationId,
                        principalTable: "AIConversations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AIConversations_EventId",
                table: "AIConversations",
                column: "EventId");

            migrationBuilder.CreateIndex(
                name: "IX_AIMessages_AIConversationId",
                table: "AIMessages",
                column: "AIConversationId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "AIMessages");
            migrationBuilder.DropTable(name: "AIConversations");
        }
    }
}
